const VOCAB = [

  // PRONOUNS
  { dev: "म", rom: "ma", eng: "I / me", category: "pronouns" },
  { dev: "तिमी", rom: "timi", eng: "you (informal)", category: "pronouns" },
  { dev: "ऊ", rom: "u", eng: "he / she (informal)", category: "pronouns" },
  { dev: "उनी", rom: "uni", eng: "he / she (respectful)", category: "pronouns" },
  { dev: "तपाईं", rom: "tapaaiin", eng: "you (formal/polite)", category: "pronouns" },
  { dev: "हामी", rom: "haami", eng: "we", category: "pronouns" },
  { dev: "तिमीहरू", rom: "timiharuu", eng: "you all (informal)", category: "pronouns" },
  { dev: "उनीहरू", rom: "uniharuu", eng: "they", category: "pronouns" },
  { dev: "यो", rom: "yo", eng: "this / it", category: "pronouns" },
  { dev: "त्यो", rom: "tyo", eng: "that", category: "pronouns" },
  { dev: "के", rom: "ke", eng: "what", category: "pronouns" },
  { dev: "को", rom: "ko", eng: "who", category: "pronouns" },
  { dev: "कहाँ", rom: "kahaan", eng: "where", category: "pronouns" },

  // NOUNS - BASIC
  { dev: "मान्छे", rom: "maanchhe", eng: "person / people", category: "nouns-basic" },
  { dev: "घर", rom: "ghar", eng: "house / home", category: "nouns-basic" },
  { dev: "ठाउँ", rom: "thaau~", eng: "place", category: "nouns-basic" },
  { dev: "काम", rom: "kaam", eng: "work / task", category: "nouns-basic" },
  { dev: "कुरा", rom: "kuraa", eng: "thing / matter / word", category: "nouns-basic" },
  { dev: "नाम", rom: "naam", eng: "name", category: "nouns-basic" },
  { dev: "दिन", rom: "din", eng: "day", category: "nouns-basic" },
  { dev: "समय", rom: "samay", eng: "time", category: "nouns-basic" },
  { dev: "पैसा", rom: "paisaa", eng: "money", category: "nouns-basic" },
  { dev: "किताब", rom: "kitaab", eng: "book", category: "nouns-basic" },
  { dev: "बाटो", rom: "baato", eng: "road / way / path", category: "nouns-basic" },
  { dev: "पानी", rom: "paani", eng: "water", category: "nouns-basic" },
  { dev: "खाना", rom: "khaanaa", eng: "food / meal", category: "nouns-basic" },
  { dev: "साथी", rom: "saathi", eng: "friend", category: "nouns-basic" },
  { dev: "देश", rom: "desh", eng: "country", category: "nouns-basic" },
  { dev: "शहर", rom: "shahar", eng: "city / town", category: "nouns-basic" },
  { dev: "भाषा", rom: "bhaashaa", eng: "language", category: "nouns-basic" },
  { dev: "मन", rom: "man", eng: "heart / mind", category: "nouns-basic" },
  { dev: "हात", rom: "haat", eng: "hand", category: "nouns-basic" },
  { dev: "आँखा", rom: "aa~khaa", eng: "eye(s)", category: "nouns-basic" },
  { dev: "ढोका", rom: "dhokaa", eng: "door", category: "nouns-basic" },
  { dev: "झ्याल", rom: "jhyaal", eng: "window", category: "nouns-basic" },
  { dev: "कोठा", rom: "kothaa", eng: "room", category: "nouns-basic" },
  { dev: "सडक", rom: "sadak", eng: "street / road", category: "nouns-basic" },
  { dev: "माछो", rom: "maachho", eng: "fish", category: "nouns-basic" },
  { dev: "मासु", rom: "maasu", eng: "meat", category: "nouns-basic" },

  // NOUNS - SCHOOL
  { dev: "स्कूल", rom: "skuul", eng: "school", category: "nouns-school" },
  { dev: "कक्षा", rom: "kaksaa", eng: "class / classroom", category: "nouns-school" },
  { dev: "शिक्षक", rom: "shikshak", eng: "teacher (male)", category: "nouns-school" },
  { dev: "शिक्षिका", rom: "shikshikaa", eng: "teacher (female)", category: "nouns-school" },
  { dev: "विद्यार्थी", rom: "vidyaarthii", eng: "student", category: "nouns-school" },
  { dev: "परीक्षा", rom: "pariikshaa", eng: "exam / test", category: "nouns-school" },
  { dev: "गृहकार्य", rom: "grihakaarya", eng: "homework", category: "nouns-school" },
  { dev: "कलम", rom: "kalam", eng: "pen", category: "nouns-school" },
  { dev: "कापी", rom: "kaapii", eng: "notebook", category: "nouns-school" },
  { dev: "बोर्ड", rom: "bord", eng: "blackboard / board", category: "nouns-school" },
  { dev: "विषय", rom: "vishay", eng: "subject", category: "nouns-school" },
  { dev: "पुस्तकालय", rom: "pustakaalay", eng: "library", category: "nouns-school" },
  { dev: "विश्वविद्यालय", rom: "vishwavidyaalay", eng: "university", category: "nouns-school" },
  { dev: "छात्रावास", rom: "chhatraavaas", eng: "dormitory / hostel", category: "nouns-school" },
  { dev: "पाठ", rom: "paath", eng: "lesson", category: "nouns-school" },
  { dev: "प्रश्न", rom: "prashna", eng: "question", category: "nouns-school" },
  { dev: "जवाफ", rom: "javaph", eng: "answer", category: "nouns-school" },
  { dev: "नम्बर", rom: "nambar", eng: "number / grade / score", category: "nouns-school" },
  { dev: "गणित", rom: "ganiit", eng: "math", category: "nouns-school" },
  { dev: "विज्ञान", rom: "vigyaan", eng: "science", category: "nouns-school" },
  { dev: "इतिहास", rom: "itihaas", eng: "history", category: "nouns-school" },
  { dev: "अङ्ग्रेजी", rom: "angrejii", eng: "English (language)", category: "nouns-school" },
  { dev: "नेपाली", rom: "nepaalii", eng: "Nepali (language)", category: "nouns-school" },
  { dev: "पेन्सिल", rom: "pensil", eng: "pencil", category: "nouns-school" },
  { dev: "थैला", rom: "thailaa", eng: "bag", category: "nouns-school" },

  // NOUNS - FAMILY
  { dev: "परिवार", rom: "parivaar", eng: "family", category: "nouns-family" },
  { dev: "आमा", rom: "aamaa", eng: "mother", category: "nouns-family" },
  { dev: "बुवा", rom: "buwaa", eng: "father", category: "nouns-family" },
  { dev: "दाइ", rom: "daai", eng: "older brother", category: "nouns-family" },
  { dev: "दिदी", rom: "didii", eng: "older sister", category: "nouns-family" },
  { dev: "भाइ", rom: "bhaai", eng: "younger brother", category: "nouns-family" },
  { dev: "बहिनी", rom: "bahinii", eng: "younger sister", category: "nouns-family" },
  { dev: "छोरा", rom: "chhoraa", eng: "son", category: "nouns-family" },
  { dev: "छोरी", rom: "chhorii", eng: "daughter", category: "nouns-family" },
  { dev: "श्रीमान्", rom: "shriimaan", eng: "husband", category: "nouns-family" },
  { dev: "श्रीमती", rom: "shriimati", eng: "wife", category: "nouns-family" },
  { dev: "हजुरआमा", rom: "hajuraamaa", eng: "grandmother", category: "nouns-family" },
  { dev: "हजुरबुवा", rom: "hajurbuwaa", eng: "grandfather", category: "nouns-family" },
  { dev: "काका", rom: "kaakaa", eng: "uncle (father's younger brother)", category: "nouns-family" },
  { dev: "काकी", rom: "kaakii", eng: "aunt (uncle's wife)", category: "nouns-family" },
  { dev: "मामा", rom: "maamaa", eng: "uncle (mother's brother)", category: "nouns-family" },
  { dev: "फुपू", rom: "phupuu", eng: "aunt (father's sister)", category: "nouns-family" },
  { dev: "नाति", rom: "naati", eng: "grandson", category: "nouns-family" },
  { dev: "नातिनी", rom: "naatinii", eng: "granddaughter", category: "nouns-family" },
  { dev: "छिमेकी", rom: "chhimekii", eng: "neighbor", category: "nouns-family" },
  { dev: "साथी", rom: "saathi", eng: "friend", category: "nouns-family" },
  { dev: "प्रेमी", rom: "premii", eng: "boyfriend / lover (male)", category: "nouns-family" },
  { dev: "प्रेमिका", rom: "premikaa", eng: "girlfriend / lover (female)", category: "nouns-family" },
  { dev: "बच्चा", rom: "bachchaa", eng: "child / baby", category: "nouns-family" },
  { dev: "मान्छे", rom: "maanchhe", eng: "person", category: "nouns-family" },

  // NOUNS - FOOD
  { dev: "भात", rom: "bhaat", eng: "cooked rice", category: "nouns-food" },
  { dev: "दाल", rom: "daal", eng: "lentil soup", category: "nouns-food" },
  { dev: "तरकारी", rom: "tarakaariii", eng: "vegetables / vegetable curry", category: "nouns-food" },
  { dev: "रोटी", rom: "rotii", eng: "flatbread / roti", category: "nouns-food" },
  { dev: "चिया", rom: "chiyaa", eng: "tea", category: "nouns-food" },
  { dev: "दूध", rom: "duudh", eng: "milk", category: "nouns-food" },
  { dev: "फल", rom: "phal", eng: "fruit", category: "nouns-food" },
  { dev: "सुन्तला", rom: "suntalaa", eng: "orange", category: "nouns-food" },
  { dev: "स्याउ", rom: "syaau", eng: "apple", category: "nouns-food" },
  { dev: "केरा", rom: "keraa", eng: "banana", category: "nouns-food" },
  { dev: "मासु", rom: "maasu", eng: "meat", category: "nouns-food" },
  { dev: "अण्डा", rom: "andaa", eng: "egg", category: "nouns-food" },
  { dev: "नुन", rom: "nun", eng: "salt", category: "nouns-food" },
  { dev: "चिनी", rom: "chinii", eng: "sugar", category: "nouns-food" },
  { dev: "तेल", rom: "tel", eng: "oil", category: "nouns-food" },
  { dev: "मसला", rom: "masalaa", eng: "spice / spices", category: "nouns-food" },
  { dev: "रेस्टुरेन्ट", rom: "resturent", eng: "restaurant", category: "nouns-food" },
  { dev: "बजार", rom: "bajaar", eng: "market / bazaar", category: "nouns-food" },
  { dev: "भान्सा", rom: "bhaansaa", eng: "kitchen", category: "nouns-food" },
  { dev: "थाल", rom: "thaal", eng: "plate / tray", category: "nouns-food" },
  { dev: "गिलास", rom: "gilaas", eng: "glass / cup", category: "nouns-food" },
  { dev: "चम्चा", rom: "chamchaa", eng: "spoon", category: "nouns-food" },
  { dev: "मोमो", rom: "momo", eng: "momo (dumplings)", category: "nouns-food" },
  { dev: "चाउमिन", rom: "chaaumin", eng: "chow mein / noodles", category: "nouns-food" },
  { dev: "खाजा", rom: "khaajaa", eng: "snack", category: "nouns-food" },

  // NOUNS - ACTIVITIES
  { dev: "खेल", rom: "khel", eng: "game / sport", category: "nouns-activities" },
  { dev: "फुटबल", rom: "phutbal", eng: "football / soccer", category: "nouns-activities" },
  { dev: "क्रिकेट", rom: "kriket", eng: "cricket", category: "nouns-activities" },
  { dev: "सङ्गीत", rom: "sangiit", eng: "music", category: "nouns-activities" },
  { dev: "गीत", rom: "giit", eng: "song", category: "nouns-activities" },
  { dev: "नाच", rom: "naach", eng: "dance", category: "nouns-activities" },
  { dev: "सिनेमा", rom: "sinemaa", eng: "cinema / movie", category: "nouns-activities" },
  { dev: "फोटो", rom: "photo", eng: "photo / picture", category: "nouns-activities" },
  { dev: "किताब", rom: "kitaab", eng: "book", category: "nouns-activities" },
  { dev: "टेलिभिजन", rom: "telibhijan", eng: "television / TV", category: "nouns-activities" },
  { dev: "फोन", rom: "phon", eng: "phone", category: "nouns-activities" },
  { dev: "कम्प्युटर", rom: "kampyutar", eng: "computer", category: "nouns-activities" },
  { dev: "इन्टरनेट", rom: "intarnet", eng: "internet", category: "nouns-activities" },
  { dev: "पार्क", rom: "paark", eng: "park", category: "nouns-activities" },
  { dev: "पहाड", rom: "pahaad", eng: "mountain / hill", category: "nouns-activities" },
  { dev: "नदी", rom: "nadii", eng: "river", category: "nouns-activities" },
  { dev: "जङ्गल", rom: "jangal", eng: "forest / jungle", category: "nouns-activities" },
  { dev: "पौडी", rom: "paudii", eng: "swimming", category: "nouns-activities" },
  { dev: "दौड", rom: "daud", eng: "running / race", category: "nouns-activities" },
  { dev: "योग", rom: "yog", eng: "yoga", category: "nouns-activities" },
  { dev: "चित्र", rom: "chitra", eng: "picture / painting", category: "nouns-activities" },
  { dev: "बगैँचा", rom: "bagaainchaa", eng: "garden", category: "nouns-activities" },
  { dev: "पुस्तक", rom: "pustak", eng: "book", category: "nouns-activities" },
  { dev: "यात्रा", rom: "yaatraa", eng: "journey / trip", category: "nouns-activities" },
  { dev: "शौक", rom: "shauk", eng: "hobby / interest", category: "nouns-activities" },

  // NOUNS - WORK
  { dev: "कार्यालय", rom: "kaaryaalay", eng: "office", category: "nouns-work" },
  { dev: "काम", rom: "kaam", eng: "work / job", category: "nouns-work" },
  { dev: "जागिर", rom: "jaagir", eng: "job / employment", category: "nouns-work" },
  { dev: "तलब", rom: "talab", eng: "salary", category: "nouns-work" },
  { dev: "बैठक", rom: "baithak", eng: "meeting", category: "nouns-work" },
  { dev: "कम्पनी", rom: "kampanii", eng: "company", category: "nouns-work" },
  { dev: "व्यापार", rom: "vyaapaar", eng: "business / trade", category: "nouns-work" },
  { dev: "डाक्टर", rom: "daaktar", eng: "doctor", category: "nouns-work" },
  { dev: "नर्स", rom: "nars", eng: "nurse", category: "nouns-work" },
  { dev: "इञ्जिनियर", rom: "injiniyar", eng: "engineer", category: "nouns-work" },
  { dev: "वकिल", rom: "vakil", eng: "lawyer", category: "nouns-work" },
  { dev: "व्यापारी", rom: "vyaapaaarii", eng: "businessman / merchant", category: "nouns-work" },
  { dev: "किसान", rom: "kisaan", eng: "farmer", category: "nouns-work" },
  { dev: "सिपाही", rom: "sipaahii", eng: "soldier / police officer", category: "nouns-work" },
  { dev: "ड्राइभर", rom: "draaibhar", eng: "driver", category: "nouns-work" },
  { dev: "कामदार", rom: "kaamdaar", eng: "worker / laborer", category: "nouns-work" },
  { dev: "रिपोर्ट", rom: "riport", eng: "report", category: "nouns-work" },
  { dev: "प्रोजेक्ट", rom: "projekt", eng: "project", category: "nouns-work" },
  { dev: "ग्राहक", rom: "graahak", eng: "customer / client", category: "nouns-work" },
  { dev: "मालिक", rom: "maalik", eng: "owner / boss", category: "nouns-work" },
  { dev: "सहकर्मी", rom: "sahakarmii", eng: "colleague / coworker", category: "nouns-work" },
  { dev: "अस्पताल", rom: "aspatal", eng: "hospital", category: "nouns-work" },
  { dev: "पसल", rom: "pasal", eng: "shop / store", category: "nouns-work" },
  { dev: "बैंक", rom: "baink", eng: "bank", category: "nouns-work" },
  { dev: "इमेल", rom: "imel", eng: "email", category: "nouns-work" },

  // NOUNS - PARTY
  { dev: "पार्टी", rom: "paartii", eng: "party", category: "nouns-party" },
  { dev: "जन्मदिन", rom: "janmadin", eng: "birthday", category: "nouns-party" },
  { dev: "चाड", rom: "chaad", eng: "festival / holiday", category: "nouns-party" },
  { dev: "विवाह", rom: "vivaah", eng: "wedding / marriage", category: "nouns-party" },
  { dev: "उपहार", rom: "upahaar", eng: "gift / present", category: "nouns-party" },
  { dev: "केक", rom: "kek", eng: "cake", category: "nouns-party" },
  { dev: "खाजा", rom: "khaajaa", eng: "snack / food at a party", category: "nouns-party" },
  { dev: "रक्सी", rom: "raksii", eng: "alcohol / liquor", category: "nouns-party" },
  { dev: "बियर", rom: "biyar", eng: "beer", category: "nouns-party" },
  { dev: "नाच", rom: "naach", eng: "dance", category: "nouns-party" },
  { dev: "गीत", rom: "giit", eng: "song", category: "nouns-party" },
  { dev: "साथी", rom: "saathi", eng: "friend", category: "nouns-party" },
  { dev: "मेहमान", rom: "mehmaan", eng: "guest", category: "nouns-party" },
  { dev: "निमन्त्रणा", rom: "nimantranaa", eng: "invitation", category: "nouns-party" },
  { dev: "बधाई", rom: "badhaaii", eng: "congratulations", category: "nouns-party" },
  { dev: "शुभकामना", rom: "shubhakaamanaa", eng: "best wishes / greetings", category: "nouns-party" },
  { dev: "मैदान", rom: "maidaan", eng: "field / open ground / venue", category: "nouns-party" },
  { dev: "सजावट", rom: "sajaawat", eng: "decoration", category: "nouns-party" },
  { dev: "मोमबत्ती", rom: "momabattii", eng: "candle", category: "nouns-party" },
  { dev: "फोटो", rom: "photo", eng: "photo", category: "nouns-party" },
  { dev: "मनोरञ्जन", rom: "manoranjan", eng: "entertainment / fun", category: "nouns-party" },
  { dev: "समारोह", rom: "samaaroh", eng: "ceremony / event", category: "nouns-party" },
  { dev: "रात", rom: "raat", eng: "night", category: "nouns-party" },
  { dev: "खुशी", rom: "khushii", eng: "happiness / joy", category: "nouns-party" },
  { dev: "आनन्द", rom: "aanand", eng: "enjoyment / delight", category: "nouns-party" },

  // NOUNS - TRAVEL
  { dev: "यात्रा", rom: "yaatraa", eng: "journey / trip / travel", category: "nouns-travel" },
  { dev: "विमान", rom: "wimaan", eng: "airplane", category: "nouns-travel" },
  { dev: "विमानस्थल", rom: "wimaansthaal", eng: "airport", category: "nouns-travel" },
  { dev: "बस", rom: "bas", eng: "bus", category: "nouns-travel" },
  { dev: "ट्याक्सी", rom: "tyaaksii", eng: "taxi", category: "nouns-travel" },
  { dev: "ट्रेन", rom: "tren", eng: "train", category: "nouns-travel" },
  { dev: "होटल", rom: "hotal", eng: "hotel", category: "nouns-travel" },
  { dev: "टिकट", rom: "tikat", eng: "ticket", category: "nouns-travel" },
  { dev: "राहदानी", rom: "raahadaanii", eng: "passport", category: "nouns-travel" },
  { dev: "भिसा", rom: "bhisaa", eng: "visa", category: "nouns-travel" },
  { dev: "सामान", rom: "saamaan", eng: "luggage / belongings", category: "nouns-travel" },
  { dev: "नक्सा", rom: "naksaa", eng: "map", category: "nouns-travel" },
  { dev: "सिमाना", rom: "simaanaa", eng: "border / boundary", category: "nouns-travel" },
  { dev: "देश", rom: "desh", eng: "country", category: "nouns-travel" },
  { dev: "सहर", rom: "shahar", eng: "city", category: "nouns-travel" },
  { dev: "गाउँ", rom: "gaau~", eng: "village", category: "nouns-travel" },
  { dev: "पहाड", rom: "pahaad", eng: "mountain", category: "nouns-travel" },
  { dev: "समुद्र", rom: "samudra", eng: "sea / ocean", category: "nouns-travel" },
  { dev: "मन्दिर", rom: "mandir", eng: "temple", category: "nouns-travel" },
  { dev: "संग्रहालय", rom: "sangrahaalay", eng: "museum", category: "nouns-travel" },
  { dev: "गाइड", rom: "gaaid", eng: "guide", category: "nouns-travel" },
  { dev: "बाटो", rom: "baato", eng: "road / path", category: "nouns-travel" },
  { dev: "पर्यटक", rom: "paryatak", eng: "tourist", category: "nouns-travel" },
  { dev: "फर्कनु", rom: "pharkanu", eng: "to return (inf.)", category: "nouns-travel" },
  { dev: "मौसम", rom: "mausam", eng: "weather / season", category: "nouns-travel" },

  // VERBS - BASIC
  { dev: "जानु", rom: "jaanu", eng: "to go", category: "verbs-basic" },
  { dev: "आउनु", rom: "aaunu", eng: "to come", category: "verbs-basic" },
  { dev: "खानु", rom: "khaanu", eng: "to eat", category: "verbs-basic" },
  { dev: "गर्नु", rom: "garnu", eng: "to do", category: "verbs-basic" },
  { dev: "हुनु", rom: "hunu", eng: "to be", category: "verbs-basic" },
  { dev: "बोल्नु", rom: "bolnu", eng: "to speak", category: "verbs-basic" },
  { dev: "पढ्नु", rom: "padhnu", eng: "to read / study", category: "verbs-basic" },
  { dev: "लेख्नु", rom: "lekhnu", eng: "to write", category: "verbs-basic" },
  { dev: "दिनु", rom: "dinu", eng: "to give", category: "verbs-basic" },
  { dev: "लिनु", rom: "linu", eng: "to take", category: "verbs-basic" },
  { dev: "बस्नु", rom: "basnu", eng: "to sit / stay / live", category: "verbs-basic" },
  { dev: "सुन्नु", rom: "sunnu", eng: "to listen / hear", category: "verbs-basic" },
  { dev: "हेर्नु", rom: "hernu", eng: "to look / watch", category: "verbs-basic" },
  { dev: "सोच्नु", rom: "sochnu", eng: "to think", category: "verbs-basic" },
  { dev: "भन्नु", rom: "bhannu", eng: "to say / tell", category: "verbs-basic" },
  { dev: "सुत्नु", rom: "sutnu", eng: "to sleep", category: "verbs-basic" },
  { dev: "उठ्नु", rom: "uthnu", eng: "to get up / wake up", category: "verbs-basic" },
  { dev: "हिँड्नु", rom: "hii~dnu", eng: "to walk", category: "verbs-basic" },
  { dev: "दौडिनु", rom: "daudinu", eng: "to run", category: "verbs-basic" },
  { dev: "बुझ्नु", rom: "bujhnu", eng: "to understand", category: "verbs-basic" },
  { dev: "जान्नु", rom: "jaannu", eng: "to know", category: "verbs-basic" },
  { dev: "चाहनु", rom: "chaahanu", eng: "to want", category: "verbs-basic" },
  { dev: "सक्नु", rom: "saknu", eng: "to be able to / can", category: "verbs-basic" },
  { dev: "फर्कनु", rom: "pharkanu", eng: "to return / come back", category: "verbs-basic" },
  { dev: "खोल्नु", rom: "kholnu", eng: "to open", category: "verbs-basic" },
  { dev: "बन्द गर्नु", rom: "band garnu", eng: "to close", category: "verbs-basic" },
  { dev: "मन पर्नु", rom: "man parnu", eng: "to like", category: "verbs-basic" },

  // VERBS - SCHOOL
  { dev: "पढ्नु", rom: "padhnu", eng: "to study / read", category: "verbs-school" },
  { dev: "लेख्नु", rom: "lekhnu", eng: "to write", category: "verbs-school" },
  { dev: "सिक्नु", rom: "siknu", eng: "to learn", category: "verbs-school" },
  { dev: "सिकाउनु", rom: "sikaunu", eng: "to teach", category: "verbs-school" },
  { dev: "सोध्नु", rom: "sodhnu", eng: "to ask", category: "verbs-school" },
  { dev: "जवाफ दिनु", rom: "javaph dinu", eng: "to answer", category: "verbs-school" },
  { dev: "बुझ्नु", rom: "bujhnu", eng: "to understand", category: "verbs-school" },
  { dev: "याद गर्नु", rom: "yaad garnu", eng: "to remember / memorize", category: "verbs-school" },
  { dev: "परीक्षा दिनु", rom: "pariikshaa dinu", eng: "to take an exam", category: "verbs-school" },
  { dev: "पास गर्नु", rom: "paas garnu", eng: "to pass (an exam)", category: "verbs-school" },
  { dev: "फेल हुनु", rom: "phel hunu", eng: "to fail", category: "verbs-school" },
  { dev: "स्नातक गर्नु", rom: "snaatok garnu", eng: "to graduate", category: "verbs-school" },

  // VERBS - FAMILY
  { dev: "माया गर्नु", rom: "maayaa garnu", eng: "to love", category: "verbs-family" },
  { dev: "भेट्नु", rom: "bhetnu", eng: "to meet", category: "verbs-family" },
  { dev: "हेर्नु", rom: "hernu", eng: "to look after / care for", category: "verbs-family" },
  { dev: "खेल्नु", rom: "khelnu", eng: "to play", category: "verbs-family" },
  { dev: "रुनु", rom: "runu", eng: "to cry", category: "verbs-family" },
  { dev: "हाँस्नु", rom: "haa~snu", eng: "to laugh / smile", category: "verbs-family" },
  { dev: "झगडा गर्नु", rom: "jhagadaa garnu", eng: "to argue / fight", category: "verbs-family" },
  { dev: "सघाउनु", rom: "saghaunu", eng: "to help", category: "verbs-family" },
  { dev: "बिहे गर्नु", rom: "bihe garnu", eng: "to get married", category: "verbs-family" },
  { dev: "जन्माउनु", rom: "janmaunu", eng: "to give birth", category: "verbs-family" },
  { dev: "हुर्कनु", rom: "hurkanu", eng: "to grow up", category: "verbs-family" },
  { dev: "बोलाउनु", rom: "bolaunu", eng: "to call / invite", category: "verbs-family" },

  // VERBS - FOOD
  { dev: "खानु", rom: "khaanu", eng: "to eat", category: "verbs-food" },
  { dev: "पिउनु", rom: "piunu", eng: "to drink", category: "verbs-food" },
  { dev: "पकाउनु", rom: "pakaunu", eng: "to cook", category: "verbs-food" },
  { dev: "किन्नु", rom: "kinnu", eng: "to buy", category: "verbs-food" },
  { dev: "बेच्नु", rom: "bechnu", eng: "to sell", category: "verbs-food" },
  { dev: "माग्नु", rom: "maagnu", eng: "to ask for / order", category: "verbs-food" },
  { dev: "ल्याउनु", rom: "lyaaunu", eng: "to bring", category: "verbs-food" },
  { dev: "दिनु", rom: "dinu", eng: "to serve / give", category: "verbs-food" },
  { dev: "मिठो लाग्नु", rom: "mitho laagnu", eng: "to taste good / find delicious", category: "verbs-food" },
  { dev: "भोक लाग्नु", rom: "bhok laagnu", eng: "to feel hungry", category: "verbs-food" },
  { dev: "तिर्खा लाग्नु", rom: "tirkhaa laagnu", eng: "to feel thirsty", category: "verbs-food" },
  { dev: "काट्नु", rom: "kaatnu", eng: "to cut / chop", category: "verbs-food" },

  // VERBS - ACTIVITIES
  { dev: "खेल्नु", rom: "khelnu", eng: "to play", category: "verbs-activities" },
  { dev: "गाउनु", rom: "gaunu", eng: "to sing", category: "verbs-activities" },
  { dev: "नाच्नु", rom: "naachnu", eng: "to dance", category: "verbs-activities" },
  { dev: "हेर्नु", rom: "hernu", eng: "to watch", category: "verbs-activities" },
  { dev: "सुन्नु", rom: "sunnu", eng: "to listen", category: "verbs-activities" },
  { dev: "पढ्नु", rom: "padhnu", eng: "to read", category: "verbs-activities" },
  { dev: "कोर्नु", rom: "kornu", eng: "to draw / paint", category: "verbs-activities" },
  { dev: "तार्नु", rom: "taarnu", eng: "to swim", category: "verbs-activities" },
  { dev: "दौडिनु", rom: "daudinu", eng: "to run", category: "verbs-activities" },
  { dev: "हिँड्नु", rom: "hii~dnu", eng: "to walk / hike", category: "verbs-activities" },
  { dev: "फोटो खिच्नु", rom: "photo khichnu", eng: "to take a photo", category: "verbs-activities" },
  { dev: "यात्रा गर्नु", rom: "yaatraa garnu", eng: "to travel", category: "verbs-activities" },

  // VERBS - WORK
  { dev: "काम गर्नु", rom: "kaam garnu", eng: "to work", category: "verbs-work" },
  { dev: "बैठक गर्नु", rom: "baithak garnu", eng: "to have a meeting", category: "verbs-work" },
  { dev: "पठाउनु", rom: "pathaunu", eng: "to send", category: "verbs-work" },
  { dev: "प्राप्त गर्नु", rom: "praapt garnu", eng: "to receive", category: "verbs-work" },
  { dev: "सम्झाउनु", rom: "samjhaunu", eng: "to explain", category: "verbs-work" },
  { dev: "निर्णय गर्नु", rom: "nirnay garnu", eng: "to decide", category: "verbs-work" },
  { dev: "सुरु गर्नु", rom: "suru garnu", eng: "to start / begin", category: "verbs-work" },
  { dev: "सिद्ध्याउनु", rom: "siddhyaunu", eng: "to finish / complete", category: "verbs-work" },
  { dev: "तिर्नु", rom: "tirnu", eng: "to pay", category: "verbs-work" },
  { dev: "कमाउनु", rom: "kamaunu", eng: "to earn", category: "verbs-work" },
  { dev: "बढावा दिनु", rom: "badhaawaa dinu", eng: "to promote", category: "verbs-work" },
  { dev: "जाँच्नु", rom: "jaa~chnu", eng: "to check / inspect", category: "verbs-work" },

  // VERBS - PARTY
  { dev: "मनाउनु", rom: "manaunu", eng: "to celebrate", category: "verbs-party" },
  { dev: "निमन्त्रणा दिनु", rom: "nimantranaa dinu", eng: "to invite", category: "verbs-party" },
  { dev: "आउनु", rom: "aaunu", eng: "to come / attend", category: "verbs-party" },
  { dev: "नाच्नु", rom: "naachnu", eng: "to dance", category: "verbs-party" },
  { dev: "गाउनु", rom: "gaunu", eng: "to sing", category: "verbs-party" },
  { dev: "खानु", rom: "khaanu", eng: "to eat", category: "verbs-party" },
  { dev: "पिउनु", rom: "piunu", eng: "to drink", category: "verbs-party" },
  { dev: "उपहार दिनु", rom: "upahaar dinu", eng: "to give a gift", category: "verbs-party" },
  { dev: "बधाई दिनु", rom: "badhaaii dinu", eng: "to congratulate", category: "verbs-party" },
  { dev: "रमाउनु", rom: "ramaunu", eng: "to enjoy / have fun", category: "verbs-party" },
  { dev: "भेट्नु", rom: "bhetnu", eng: "to meet", category: "verbs-party" },
  { dev: "फोटो खिच्नु", rom: "photo khichnu", eng: "to take photos", category: "verbs-party" },

  // VERBS - TRAVEL
  { dev: "यात्रा गर्नु", rom: "yaatraa garnu", eng: "to travel", category: "verbs-travel" },
  { dev: "जानु", rom: "jaanu", eng: "to go", category: "verbs-travel" },
  { dev: "आउनु", rom: "aaunu", eng: "to come / arrive", category: "verbs-travel" },
  { dev: "फर्कनु", rom: "pharkanu", eng: "to return", category: "verbs-travel" },
  { dev: "बस्नु", rom: "basnu", eng: "to stay", category: "verbs-travel" },
  { dev: "बुक गर्नु", rom: "buk garnu", eng: "to book / reserve", category: "verbs-travel" },
  { dev: "पुग्नु", rom: "pugnu", eng: "to arrive / reach", category: "verbs-travel" },
  { dev: "हराउनु", rom: "haraunu", eng: "to get lost", category: "verbs-travel" },
  { dev: "सोध्नु", rom: "sodhnu", eng: "to ask (for directions)", category: "verbs-travel" },
  { dev: "हेर्नु", rom: "hernu", eng: "to see / visit (a sight)", category: "verbs-travel" },
  { dev: "किन्नु", rom: "kinnu", eng: "to buy (souvenirs)", category: "verbs-travel" },
  { dev: "फोटो खिच्नु", rom: "photo khichnu", eng: "to take photos", category: "verbs-travel" },

  // TIME
  { dev: "अहिले", rom: "ahile", eng: "now / right now", category: "time" },
  { dev: "आज", rom: "aaj", eng: "today", category: "time" },
  { dev: "भोलि", rom: "bholi", eng: "tomorrow", category: "time" },
  { dev: "हिजो", rom: "hijo", eng: "yesterday", category: "time" },
  { dev: "पर्सि", rom: "parsi", eng: "day after tomorrow", category: "time" },
  { dev: "अस्ति", rom: "asti", eng: "day before yesterday", category: "time" },
  { dev: "बिहान", rom: "bihaan", eng: "morning", category: "time" },
  { dev: "दिउँसो", rom: "diu~so", eng: "afternoon", category: "time" },
  { dev: "साँझ", rom: "saa~jh", eng: "evening", category: "time" },
  { dev: "रात", rom: "raat", eng: "night", category: "time" },
  { dev: "हप्ता", rom: "haptaa", eng: "week", category: "time" },
  { dev: "महिना", rom: "mahinaa", eng: "month", category: "time" },
  { dev: "वर्ष", rom: "varsha", eng: "year", category: "time" },
  { dev: "अर्को", rom: "arko", eng: "next / another", category: "time" },
  { dev: "पछि", rom: "pachhi", eng: "later / after", category: "time" },
  { dev: "पहिले", rom: "pahile", eng: "before / earlier / first", category: "time" },
  { dev: "सधैं", rom: "sadhai~", eng: "always", category: "time" },
  { dev: "कहिलेकाहीँ", rom: "kahilekahii~", eng: "sometimes", category: "time" },
  { dev: "कहिल्यै", rom: "kahilyai", eng: "never", category: "time" },
  { dev: "अब", rom: "ab", eng: "now / from now", category: "time" },
  { dev: "छिट्टै", rom: "chhittai", eng: "soon", category: "time" },
  { dev: "ढिलो", rom: "dhilo", eng: "late / slow", category: "time" },

  // GRAMMATICAL
  { dev: "र", rom: "ra", eng: "and", category: "grammatical" },
  { dev: "तर", rom: "tara", eng: "but", category: "grammatical" },
  { dev: "किनभने", rom: "kinabhane", eng: "because", category: "grammatical" },
  { dev: "यदि", rom: "yadi", eng: "if", category: "grammatical" },
  { dev: "भने", rom: "bhane", eng: "then / if...then", category: "grammatical" },
  { dev: "वा", rom: "waa", eng: "or", category: "grammatical" },
  { dev: "पनि", rom: "pani", eng: "also / too / even", category: "grammatical" },
  { dev: "मात्र", rom: "maatra", eng: "only / just", category: "grammatical" },
  { dev: "धेरै", rom: "dherai", eng: "many / much / very", category: "grammatical" },
  { dev: "थोरै", rom: "thorai", eng: "a little / few", category: "grammatical" },
  { dev: "सबै", rom: "sabai", eng: "all / everyone", category: "grammatical" },
  { dev: "केही", rom: "kehii", eng: "some / something / a few", category: "grammatical" },
  { dev: "कुनै", rom: "kunai", eng: "any / some", category: "grammatical" },
  { dev: "यहाँ", rom: "yahaa~", eng: "here", category: "grammatical" },
  { dev: "त्यहाँ", rom: "tyahaa~", eng: "there", category: "grammatical" },
  { dev: "माथि", rom: "maathi", eng: "above / up / upstairs", category: "grammatical" },
  { dev: "तल", rom: "tala", eng: "below / down / downstairs", category: "grammatical" },
  { dev: "अगाडि", rom: "agaadi", eng: "in front of / before / ahead", category: "grammatical" },
  { dev: "पछाडि", rom: "pachhaadi", eng: "behind / after", category: "grammatical" },
  { dev: "नजिक", rom: "najik", eng: "near / close", category: "grammatical" },
  { dev: "टाढा", rom: "taadha", eng: "far", category: "grammatical" },
  { dev: "सँगै", rom: "sangai", eng: "together / with", category: "grammatical" },
  { dev: "बिना", rom: "binaa", eng: "without", category: "grammatical" },
  { dev: "को लागि", rom: "ko laagi", eng: "for", category: "grammatical" },
  { dev: "बारे", rom: "baare", eng: "about / regarding", category: "grammatical" },
  { dev: "जस्तो", rom: "jasto", eng: "like / as / such as", category: "grammatical" },
  { dev: "भन्दा", rom: "bhandaa", eng: "than (comparative)", category: "grammatical" },
  { dev: "नै", rom: "nai", eng: "indeed / exactly / emphatic particle", category: "grammatical" },

  // NUMBERS
  { dev: "शून्य", rom: "shuunya", eng: "zero", category: "numbers" },
  { dev: "एक", rom: "ek", eng: "one", category: "numbers" },
  { dev: "दुई", rom: "dui", eng: "two", category: "numbers" },
  { dev: "तीन", rom: "tiin", eng: "three", category: "numbers" },
  { dev: "चार", rom: "chaar", eng: "four", category: "numbers" },
  { dev: "पाँच", rom: "paa~ch", eng: "five", category: "numbers" },
  { dev: "छ", rom: "chha", eng: "six", category: "numbers" },
  { dev: "सात", rom: "saat", eng: "seven", category: "numbers" },
  { dev: "आठ", rom: "aath", eng: "eight", category: "numbers" },
  { dev: "नौ", rom: "nau", eng: "nine", category: "numbers" },
  { dev: "दस", rom: "das", eng: "ten", category: "numbers" },
  { dev: "एघार", rom: "eghaar", eng: "eleven", category: "numbers" },
  { dev: "बाह्र", rom: "baahro", eng: "twelve", category: "numbers" },
  { dev: "बिस", rom: "bis", eng: "twenty", category: "numbers" },
  { dev: "पचास", rom: "pachaas", eng: "fifty", category: "numbers" },
  { dev: "सय", rom: "say", eng: "one hundred", category: "numbers" },
  { dev: "हजार", rom: "hajaar", eng: "one thousand", category: "numbers" },
  { dev: "पहिलो", rom: "pahilo", eng: "first", category: "numbers" },
  { dev: "दोस्रो", rom: "dosro", eng: "second", category: "numbers" },
  { dev: "तेस्रो", rom: "tesro", eng: "third", category: "numbers" },

  // COLORS
  { dev: "रातो", rom: "raato", eng: "red", category: "colors" },
  { dev: "नीलो", rom: "niilo", eng: "blue", category: "colors" },
  { dev: "हरियो", rom: "hariyo", eng: "green", category: "colors" },
  { dev: "पहेँलो", rom: "pahelo", eng: "yellow", category: "colors" },
  { dev: "सेतो", rom: "seto", eng: "white", category: "colors" },
  { dev: "कालो", rom: "kaalo", eng: "black", category: "colors" },
  { dev: "खैरो", rom: "khairo", eng: "brown", category: "colors" },
  { dev: "सुन्तले", rom: "suntale", eng: "orange (color)", category: "colors" },
  { dev: "गुलाबी", rom: "gulaabii", eng: "pink", category: "colors" },
  { dev: "बैजनी", rom: "baijaniii", eng: "purple", category: "colors" },
  { dev: "खरानी", rom: "kharaanii", eng: "grey", category: "colors" },
  { dev: "सुनौलो", rom: "sunaulo", eng: "golden", category: "colors" },

];

const SENTENCES = [

  // ── BASIC (20) ──────────────────────────────────────────────────────────────
  // Coverage: all pronouns × core verbs (जानु, आउनु, खानु, गर्नु, हुनु, बोल्नु, दिनु, बस्नु)
  // Present tense conjugations:
  //   म → -छु    तिमी → -छौ    ऊ → -छ    उनी → -छन्/-छिन्
  //   तपाईं → -नुहुन्छ    हामी → -छौं    उनीहरू → -छन्
  { dev: "म घर जान्छु।", rom: "Ma ghar jaanchhu.", eng: "I go home.", tense: "present", theme: "basic" },
  { dev: "तिमी कहाँ जान्छौ?", rom: "Timi kahaa~ jaanchhou?", eng: "Where do you go?", tense: "present", theme: "basic" },
  { dev: "ऊ बजार जान्छ।", rom: "U bajaar jaanchha.", eng: "He goes to the market.", tense: "present", theme: "basic" },
  { dev: "उनी स्कूल जान्छिन्।", rom: "Uni skuul jaanchhinn.", eng: "She goes to school.", tense: "present", theme: "basic" },
  { dev: "तपाईं कहाँ जानुहुन्छ?", rom: "Tapaaiin kahaa~ jaanuhunchha?", eng: "Where do you go? (polite)", tense: "present", theme: "basic" },
  { dev: "हामी घर जान्छौं।", rom: "Haami ghar jaanchhau~.", eng: "We go home.", tense: "present", theme: "basic" },
  { dev: "उनीहरू बजार जान्छन्।", rom: "Uniharuu bajaar jaanchhann.", eng: "They go to the market.", tense: "present", theme: "basic" },
  { dev: "म खाना खान्छु।", rom: "Ma khaanaa khaanchhu.", eng: "I eat food.", tense: "present", theme: "basic" },
  { dev: "तिमी मासु खान्छौ?", rom: "Timi maasu khaanchhau?", eng: "Do you eat meat?", tense: "present", theme: "basic" },
  { dev: "ऊ भात खान्छ।", rom: "U bhaat khaanchha.", eng: "He eats rice.", tense: "present", theme: "basic" },
  { dev: "उनी तरकारी खान्छिन्।", rom: "Uni tarakaariii khaanchhinn.", eng: "She eats vegetables.", tense: "present", theme: "basic" },
  { dev: "हामी साँझ खाना खान्छौं।", rom: "Haami saa~jh khaanaa khaanchhau~.", eng: "We eat dinner in the evening.", tense: "present", theme: "basic" },
  { dev: "म नेपाली बोल्छु।", rom: "Ma nepaalii bolchhu.", eng: "I speak Nepali.", tense: "present", theme: "basic" },
  { dev: "तिमी अङ्ग्रेजी बोल्छौ?", rom: "Timi angrejii bolchhau?", eng: "Do you speak English?", tense: "present", theme: "basic" },
  { dev: "ऊ राम्रोसँग बोल्छ।", rom: "U raamrosanga bolchha.", eng: "He speaks well.", tense: "present", theme: "basic" },
  { dev: "तपाईं नेपाली बोल्नुहुन्छ?", rom: "Tapaaiin nepaalii bolnuhunchha?", eng: "Do you speak Nepali? (polite)", tense: "present", theme: "basic" },
  { dev: "म पैसा दिन्छु।", rom: "Ma paisaa dinchhu.", eng: "I give money.", tense: "present", theme: "basic" },
  { dev: "उनी किताब दिन्छन्।", rom: "Uni kitaab dinchhan.", eng: "He gives a book.", tense: "present", theme: "basic" },
  { dev: "हामी यहाँ बस्छौं।", rom: "Haami yahaa~ baschhau~.", eng: "We live here.", tense: "present", theme: "basic" },
  { dev: "उनीहरू काठमाडौंमा बस्छन्।", rom: "Uniharuu kaathamaadau~maa baschhan.", eng: "They live in Kathmandu.", tense: "present", theme: "basic" },

  // ── SCHOOL (20) ──────────────────────────────────────────────────────────────
  { dev: "म स्कूल जान्छु।", rom: "Ma skuul jaanchhu.", eng: "I go to school.", tense: "present", theme: "school" },
  { dev: "उनी गणित पढाउँछिन्।", rom: "Uni ganiit padhaau~chhinn.", eng: "She teaches math.", tense: "present", theme: "school" },
  { dev: "हामी कक्षामा बस्छौं।", rom: "Haami kaksaamaa baschau~.", eng: "We sit in the classroom.", tense: "present", theme: "school" },
  { dev: "म गृहकार्य गर्छु।", rom: "Ma grihakaarya garchhu.", eng: "I do homework.", tense: "present", theme: "school" },
  { dev: "विद्यार्थीले प्रश्न सोध्छ।", rom: "Vidyaarthiile prashna sodhchha.", eng: "The student asks a question.", tense: "present", theme: "school" },
  { dev: "शिक्षकले जवाफ दिनुहुन्छ।", rom: "Shikshakle javaph dinuhunchha.", eng: "The teacher gives an answer.", tense: "present", theme: "school" },
  { dev: "म परीक्षाको लागि पढ्छु।", rom: "Ma pariikshaa ko laagi padhchhu.", eng: "I study for the exam.", tense: "present", theme: "school" },
  { dev: "उनीहरूले परीक्षा दिए।", rom: "Uniharuule pariikshaa die.", eng: "They took the exam.", tense: "past", theme: "school" },
  { dev: "मैले गणित राम्रोसँग बुझिनँ।", rom: "Maile ganiit raamrosanga bujhinan~.", eng: "I did not understand math well.", tense: "past", theme: "school" },
  { dev: "ऊ पुस्तकालयमा किताब पढ्छ।", rom: "U pustakaalay maa kitaab padhchha.", eng: "He reads books in the library.", tense: "present", theme: "school" },
  { dev: "हामीले अङ्ग्रेजी सिक्यौं।", rom: "Haamilе angrejii sikyau~.", eng: "We learned English.", tense: "past", theme: "school" },
  { dev: "उनी राम्रो विद्यार्थी हुन्।", rom: "Uni raamro vidyaarthii hun.", eng: "She is a good student.", tense: "present", theme: "school" },
  { dev: "म अर्को हप्ता परीक्षा दिनेछु।", rom: "Ma arko haptaa pariikshaa dinechhu.", eng: "I will take the exam next week.", tense: "future", theme: "school" },
  { dev: "कक्षामा धेरै विद्यार्थी छन्।", rom: "Kaksaamaa dherai vidyaarthii chhan.", eng: "There are many students in the class.", tense: "present", theme: "school" },
  { dev: "शिक्षिकाले बोर्डमा लेख्नुभयो।", rom: "Shikshikaaले bordmaa lekhunubhayo.", eng: "The teacher wrote on the board.", tense: "past", theme: "school" },
  { dev: "मैले आफ्नो कापीमा लेखें।", rom: "Maile aaphno kaapii maa lekhe~.", eng: "I wrote in my notebook.", tense: "past", theme: "school" },
  { dev: "ऊ विश्वविद्यालय जानेछ।", rom: "U vishwavidyaalay jaanechha.", eng: "He will go to university.", tense: "future", theme: "school" },
  { dev: "तिमीले थैला ल्यायौ?", rom: "Timiile thailaa lyaayau?", eng: "Did you bring your bag?", tense: "past", theme: "school" },
  { dev: "हामी भोलि स्कूल जानेछौं।", rom: "Haami bholi skuul jaanechhau~.", eng: "We will go to school tomorrow.", tense: "future", theme: "school" },
  { dev: "उनीहरूले राम्रो नम्बर ल्याए।", rom: "Uniharuule raamro nambar lyaae.", eng: "They got good grades.", tense: "past", theme: "school" },

  // ── FAMILY (20) ──────────────────────────────────────────────────────────────
  { dev: "मेरो परिवार ठूलो छ।", rom: "Mero parivaar thuulo chha.", eng: "My family is big.", tense: "present", theme: "family" },
  { dev: "मेरी आमा खाना पकाउनुहुन्छ।", rom: "Merii aamaa khaanaa pakaaunuhunchha.", eng: "My mother cooks food.", tense: "present", theme: "family" },
  { dev: "मेरो बुवा काम गर्नुहुन्छ।", rom: "Mero buwaa kaam garnuhunchha.", eng: "My father works.", tense: "present", theme: "family" },
  { dev: "मेरो दाइ विश्वविद्यालयमा पढ्छ।", rom: "Mero daai vishwavidyaalay maa padhchha.", eng: "My older brother studies at university.", tense: "present", theme: "family" },
  { dev: "मेरी दिदी डाक्टर हुनुहुन्छ।", rom: "Merii didii daaktar hunuhunchha.", eng: "My older sister is a doctor.", tense: "present", theme: "family" },
  { dev: "मेरो भाइ अहिले सुत्दैछ।", rom: "Mero bhaai ahile sutdaichha.", eng: "My younger brother is sleeping right now.", tense: "present", theme: "family" },
  { dev: "हाम्रो परिवार सँगै खाना खान्छ।", rom: "Haamro parivaar sangai khaanaa khaanchha.", eng: "Our family eats together.", tense: "present", theme: "family" },
  { dev: "हजुरआमाले मलाई माया गर्नुहुन्छ।", rom: "Hajuraamaale malaaiii maayaa garnuhunchha.", eng: "My grandmother loves me.", tense: "present", theme: "family" },
  { dev: "हजुरबुवा गाउँमा बस्नुहुन्छ।", rom: "Hajurbuwaа gaau~maa basnuhunchha.", eng: "My grandfather lives in the village.", tense: "present", theme: "family" },
  { dev: "मेरो छोरा स्कूल जान्छ।", rom: "Mero chhoraa skuul jaanchha.", eng: "My son goes to school.", tense: "present", theme: "family" },
  { dev: "उनको श्रीमती शिक्षिका हुनुहुन्छ।", rom: "Unko shriimati shikshikaa hunuhunchha.", eng: "His wife is a teacher.", tense: "present", theme: "family" },
  { dev: "मैले आफ्नो साथीलाई फोन गरें।", rom: "Maile aaphno saathilaaiii phon garen.", eng: "I called my friend.", tense: "past", theme: "family" },
  { dev: "हामीले आमाको जन्मदिन मनायौं।", rom: "Haamiile aamaako janmadin manaayau~.", eng: "We celebrated mother's birthday.", tense: "past", theme: "family" },
  { dev: "मेरो बहिनी रुँदैछे।", rom: "Mero bahiniii ru~daichhe.", eng: "My younger sister is crying.", tense: "present", theme: "family" },
  { dev: "बच्चाहरू खेल्दैछन्।", rom: "Bachchaaharu kheldaichhan.", eng: "The children are playing.", tense: "present", theme: "family" },
  { dev: "काकाले मलाई उपहार दिनुभयो।", rom: "Kaakaaले malaaiii upahaar dinubhayo.", eng: "My uncle gave me a gift.", tense: "past", theme: "family" },
  { dev: "मेरो परिवार भोलि आउनेछ।", rom: "Mero parivaar bholi aaunechha.", eng: "My family will come tomorrow.", tense: "future", theme: "family" },
  { dev: "दाइदिदीहरू सँगै बस्छन्।", rom: "Daaididiiharu sangai baschhan.", eng: "The older siblings live together.", tense: "present", theme: "family" },
  { dev: "उनीहरूले बिहे गर्नेछन्।", rom: "Uniharuule bihe garnechhan.", eng: "They will get married.", tense: "future", theme: "family" },
  { dev: "मेरी आमाले राम्रो खाना पकाउनुभयो।", rom: "Merii aamaale raamro khaanaa pakaaunubhayo.", eng: "My mother cooked good food.", tense: "past", theme: "family" },

  // ── FOOD (20) ──────────────────────────────────────────────────────────────
  { dev: "मलाई भोक लाग्यो।", rom: "Malaaiii bhok laagiyo.", eng: "I am hungry.", tense: "past", theme: "food" },
  { dev: "म चिया पिउँछु।", rom: "Ma chiyaa piu~chhu.", eng: "I drink tea.", tense: "present", theme: "food" },
  { dev: "उनले मासु पकाउनुभयो।", rom: "Unle maasu pakaaunubhayo.", eng: "He/she cooked meat.", tense: "past", theme: "food" },
  { dev: "हामी रेस्टुरेन्टमा खाना खान्छौं।", rom: "Haami resturents maa khaanaa khaanchhau~.", eng: "We eat at a restaurant.", tense: "present", theme: "food" },
  { dev: "मलाई मोमो धेरै मन पर्छ।", rom: "Malaaiii momo dherai man parchha.", eng: "I really like momos.", tense: "present", theme: "food" },
  { dev: "ऊ बजारमा तरकारी किन्छ।", rom: "U bajaar maa tarakaariii kinchha.", eng: "He buys vegetables at the market.", tense: "present", theme: "food" },
  { dev: "मैले भात र दाल खाएँ।", rom: "Maile bhaat ra daal khaae~.", eng: "I ate rice and lentil soup.", tense: "past", theme: "food" },
  { dev: "यो खाना मिठो छ।", rom: "Yo khaanaa mitho chha.", eng: "This food is delicious.", tense: "present", theme: "food" },
  { dev: "उनी भान्सामा पकाउँदैछिन्।", rom: "Uni bhaansaa maa pakaau~daichhinn.", eng: "She is cooking in the kitchen.", tense: "present", theme: "food" },
  { dev: "के तिमीलाई तिर्खा लाग्यो?", rom: "Ke timilaaiii tirkhaa laagiyo?", eng: "Are you thirsty?", tense: "past", theme: "food" },
  { dev: "म पानी पिउनेछु।", rom: "Ma paanii piunchhu.", eng: "I will drink water.", tense: "future", theme: "food" },
  { dev: "उनले चिनी र दूध हालेर चिया बनाउनुभयो।", rom: "Unle chinii ra duudh haaler chiyaa banaaunubhayo.", eng: "He/she made tea with sugar and milk.", tense: "past", theme: "food" },
  { dev: "हामीले रेस्टुरेन्टमा खाना अर्डर गर्यौं।", rom: "Haamiile resturentmaa khaanaa ardar garyau~.", eng: "We ordered food at the restaurant.", tense: "past", theme: "food" },
  { dev: "फलफूल स्वस्थ हुन्छ।", rom: "Phalphuul swastha hunchha.", eng: "Fruit is healthy.", tense: "present", theme: "food" },
  { dev: "मलाई मसालेदार खाना मन पर्दैन।", rom: "Malaaiii masaledaar khaanaa man pardaina.", eng: "I don't like spicy food.", tense: "present", theme: "food" },
  { dev: "उनीहरू बिहान चिया पिउँछन्।", rom: "Uniharuu bihaan chiyaa piu~chhan.", eng: "They drink tea in the morning.", tense: "present", theme: "food" },
  { dev: "मैले अण्डा र रोटी खाएँ।", rom: "Maile andaa ra rotii khaae~.", eng: "I ate eggs and flatbread.", tense: "past", theme: "food" },
  { dev: "ऊ भोलि खाना पकाउनेछ।", rom: "U bholi khaanaa pakaaunechha.", eng: "He will cook food tomorrow.", tense: "future", theme: "food" },
  { dev: "हाम्रो भान्साघरमा धेरै मसला छ।", rom: "Haamro bhaansaaghar maa dherai masalaa chha.", eng: "There are many spices in our kitchen.", tense: "present", theme: "food" },
  { dev: "तिमीलाई के खाना मन पर्छ?", rom: "Timilaaiii ke khaanaa man parchha?", eng: "What food do you like?", tense: "present", theme: "food" },

  // ── ACTIVITIES (20) ──────────────────────────────────────────────────────────────
  { dev: "म फुटबल खेल्छु।", rom: "Ma phutbal khelchhu.", eng: "I play football.", tense: "present", theme: "activities" },
  { dev: "उनी सङ्गीत सुन्छिन्।", rom: "Uni sangiit sunchhinn.", eng: "She listens to music.", tense: "present", theme: "activities" },
  { dev: "हामी हिजो सिनेमा हेर्यौं।", rom: "Haami hijo sinemaa heryau~.", eng: "We watched a movie yesterday.", tense: "past", theme: "activities" },
  { dev: "ऊ राम्रोसँग गाउँछ।", rom: "U raamrosanga gaunchha.", eng: "He sings well.", tense: "present", theme: "activities" },
  { dev: "म बिहान दौडिन्छु।", rom: "Ma bihaan daudinchhu.", eng: "I run in the morning.", tense: "present", theme: "activities" },
  { dev: "उनीहरू पार्कमा हिँड्छन्।", rom: "Uniharuu paarkmaa hii~dchhan.", eng: "They walk in the park.", tense: "present", theme: "activities" },
  { dev: "मलाई नाच्न मन पर्छ।", rom: "Malaaiii naachna man parchha.", eng: "I like to dance.", tense: "present", theme: "activities" },
  { dev: "उनले फोटो खिचे।", rom: "Unle photo khichhe.", eng: "He/she took photos.", tense: "past", theme: "activities" },
  { dev: "हामी भोलि पहाड जानेछौं।", rom: "Haami bholi pahaad jaanechhau~.", eng: "We will go to the mountains tomorrow.", tense: "future", theme: "activities" },
  { dev: "ऊ किताब पढ्दैछ।", rom: "U kitaab padhdaichha.", eng: "He is reading a book.", tense: "present", theme: "activities" },
  { dev: "मैले नदीमा पौडी खेलें।", rom: "Maile nadiimaa paudii khele~.", eng: "I swam in the river.", tense: "past", theme: "activities" },
  { dev: "तिमीलाई कुन खेल मन पर्छ?", rom: "Timilaaiii kun khel man parchha?", eng: "Which sport do you like?", tense: "present", theme: "activities" },
  { dev: "उनी योग गर्छिन्।", rom: "Uni yog garchhinn.", eng: "She does yoga.", tense: "present", theme: "activities" },
  { dev: "हामी क्रिकेट हेर्न जानेछौं।", rom: "Haami kriket herna jaanechhau~.", eng: "We will go to watch cricket.", tense: "future", theme: "activities" },
  { dev: "मलाई सङ्गीत धेरै मन पर्छ।", rom: "Malaaiii sangiit dherai man parchha.", eng: "I like music very much.", tense: "present", theme: "activities" },
  { dev: "उनीहरूले बगैँचामा काम गरे।", rom: "Uniharuule bagaainchaamaa kaam gare.", eng: "They worked in the garden.", tense: "past", theme: "activities" },
  { dev: "ऊ राम्रो गीत गाउँछ।", rom: "U raamro giit gaunchha.", eng: "He sings a nice song.", tense: "present", theme: "activities" },
  { dev: "म टेलिभिजन हेर्छु।", rom: "Ma telibhijan herchhu.", eng: "I watch television.", tense: "present", theme: "activities" },
  { dev: "तिमी इन्टरनेटमा के गर्छौ?", rom: "Timi intarnetmaa ke garchhou?", eng: "What do you do on the internet?", tense: "present", theme: "activities" },
  { dev: "हामीले जङ्गलमा यात्रा गर्यौं।", rom: "Haamiile jangalmaa yaatraa garyau~.", eng: "We traveled through the forest.", tense: "past", theme: "activities" },

  // ── WORK (20) ──────────────────────────────────────────────────────────────
  { dev: "म कार्यालयमा काम गर्छु।", rom: "Ma kaaryaalaymaa kaam garchhu.", eng: "I work at the office.", tense: "present", theme: "work" },
  { dev: "उनी डाक्टर हुनुहुन्छ।", rom: "Uni daaktar hunuhunchha.", eng: "He/she is a doctor.", tense: "present", theme: "work" },
  { dev: "हाम्रो बैठक दिउँसो छ।", rom: "Haamro baithak diu~so chha.", eng: "Our meeting is in the afternoon.", tense: "present", theme: "work" },
  { dev: "मैले रिपोर्ट पठाएँ।", rom: "Maile riport pathaae~.", eng: "I sent the report.", tense: "past", theme: "work" },
  { dev: "ऊ तलब कमाउँछ।", rom: "U talab kamaau~chha.", eng: "He earns a salary.", tense: "present", theme: "work" },
  { dev: "उनीहरूले प्रोजेक्ट सिद्ध्याए।", rom: "Uniharuule projekt siddhyaae.", eng: "They finished the project.", tense: "past", theme: "work" },
  { dev: "म आफ्नो काममा व्यस्त छु।", rom: "Ma aaphno kaamman byast chhu.", eng: "I am busy with my work.", tense: "present", theme: "work" },
  { dev: "शिक्षकले कक्षा सुरु गर्नुभयो।", rom: "Shikshakle kaksaa suru garnubhayo.", eng: "The teacher started the class.", tense: "past", theme: "work" },
  { dev: "मैले ग्राहकलाई सम्झाएँ।", rom: "Maile graahaklaaii samjhaae~.", eng: "I explained to the customer.", tense: "past", theme: "work" },
  { dev: "ऊ अस्पतालमा काम गर्छ।", rom: "U aspatal maa kaam garchha.", eng: "He works at the hospital.", tense: "present", theme: "work" },
  { dev: "हामी भोलि बैठक गर्नेछौं।", rom: "Haami bholi baithak garnechhau~.", eng: "We will have a meeting tomorrow.", tense: "future", theme: "work" },
  { dev: "उनले मालिकलाई इमेल पठाउनुभयो।", rom: "Unle maaliklaaii imel pathaaunubhayo.", eng: "He/she sent an email to the boss.", tense: "past", theme: "work" },
  { dev: "म बैंकमा जान्छु।", rom: "Ma bainkmaa jaanchhu.", eng: "I go to the bank.", tense: "present", theme: "work" },
  { dev: "किसानले खेतमा काम गर्छ।", rom: "Kisaanle khetmaa kaam garchha.", eng: "The farmer works in the field.", tense: "present", theme: "work" },
  { dev: "उनी इञ्जिनियर बन्नेछन्।", rom: "Uni injiniyar bannechhan.", eng: "He will become an engineer.", tense: "future", theme: "work" },
  { dev: "मैले पसलमा सामान किनें।", rom: "Maile pasalmaa saamaan kine~.", eng: "I bought goods at the shop.", tense: "past", theme: "work" },
  { dev: "हाम्रो कम्पनी ठूलो छ।", rom: "Haamro kampanii thuulo chha.", eng: "Our company is big.", tense: "present", theme: "work" },
  { dev: "सहकर्मीले मलाई सघाए।", rom: "Sahakarmiile malaaiii saghaae.", eng: "My colleague helped me.", tense: "past", theme: "work" },
  { dev: "ऊ व्यापार गर्छ।", rom: "U vyaapaar garchha.", eng: "He does business.", tense: "present", theme: "work" },
  { dev: "मैले तलब पाएँ।", rom: "Maile talab paae~.", eng: "I received my salary.", tense: "past", theme: "work" },

  // ── PARTY (20) ──────────────────────────────────────────────────────────────
  { dev: "आज मेरो जन्मदिन हो।", rom: "Aaj mero janmadin ho.", eng: "Today is my birthday.", tense: "present", theme: "party" },
  { dev: "हामीले पार्टी मनायौं।", rom: "Haamiile paartii manaayau~.", eng: "We celebrated the party.", tense: "past", theme: "party" },
  { dev: "उनले मलाई निमन्त्रणा दिनुभयो।", rom: "Unle malaaiii nimantranaa dinubhayo.", eng: "He/she invited me.", tense: "past", theme: "party" },
  { dev: "म साथीको जन्मदिनमा जान्छु।", rom: "Ma saathiko janmadin maa jaanchhu.", eng: "I go to my friend's birthday.", tense: "present", theme: "party" },
  { dev: "उनीहरूले राम्रो गीत गाए।", rom: "Uniharuule raamro giit gaae.", eng: "They sang a nice song.", tense: "past", theme: "party" },
  { dev: "हामी सँगै नाच्यौं।", rom: "Haami sangai naachyau~.", eng: "We danced together.", tense: "past", theme: "party" },
  { dev: "मैले उनलाई उपहार दिएँ।", rom: "Maile unlaaii upahaar die~.", eng: "I gave him/her a gift.", tense: "past", theme: "party" },
  { dev: "पार्टीमा धेरै मेहमान थिए।", rom: "Paartii maa dherai mehmaan thie.", eng: "There were many guests at the party.", tense: "past", theme: "party" },
  { dev: "केकमा पाँचवटा मोमबत्ती थियो।", rom: "Kek maa paa~chvataa momabattii thiyo.", eng: "There were five candles on the cake.", tense: "past", theme: "party" },
  { dev: "हामीले धेरै फोटो खिच्यौं।", rom: "Haamiile dherai photo khichyau~.", eng: "We took many photos.", tense: "past", theme: "party" },
  { dev: "उनीहरू पार्टीमा आउनेछन्।", rom: "Uniharuu paartii maa aaunechhan.", eng: "They will come to the party.", tense: "future", theme: "party" },
  { dev: "मलाई पार्टीमा धेरै रमाइलो भयो।", rom: "Malaaiii paartii maa dherai ramailo bhayo.", eng: "I had a lot of fun at the party.", tense: "past", theme: "party" },
  { dev: "हामी विवाहमा गयौं।", rom: "Haami vivaah maa gayau~.", eng: "We went to the wedding.", tense: "past", theme: "party" },
  { dev: "मैले बधाई दिएँ।", rom: "Maile badhaaii die~.", eng: "I congratulated them.", tense: "past", theme: "party" },
  { dev: "पार्टीमा राम्रो खाजा थियो।", rom: "Paartii maa raamro khaajaa thiyo.", eng: "There was good food at the party.", tense: "past", theme: "party" },
  { dev: "उनको जन्मदिनमा शुभकामना।", rom: "Unko janmadin maa shubhakaamanaa.", eng: "Best wishes on his/her birthday.", tense: "present", theme: "party" },
  { dev: "हामीले घर सजायौं।", rom: "Haamiile ghar sajaayau~.", eng: "We decorated the house.", tense: "past", theme: "party" },
  { dev: "पार्टी राम्रो भयो।", rom: "Paartii raamro bhayo.", eng: "The party was good.", tense: "past", theme: "party" },
  { dev: "म भोलिको पार्टीमा जानेछु।", rom: "Ma bholiko paartii maa jaanechhu.", eng: "I will go to tomorrow's party.", tense: "future", theme: "party" },
  { dev: "उनीहरूले रातभर नाचे।", rom: "Uniharuule raatbhar naache.", eng: "They danced all night.", tense: "past", theme: "party" },

  // ── TRAVEL (20) ──────────────────────────────────────────────────────────────
  { dev: "म नेपाल जानेछु।", rom: "Ma nepaal jaanechhu.", eng: "I will go to Nepal.", tense: "future", theme: "travel" },
  { dev: "हामी विमानमा चढ्यौं।", rom: "Haami wimaan maa chadhyau~.", eng: "We boarded the airplane.", tense: "past", theme: "travel" },
  { dev: "उनले टिकट किन्नुभयो।", rom: "Unle tikat kinnubhayo.", eng: "He/she bought a ticket.", tense: "past", theme: "travel" },
  { dev: "मेरो राहदानी कहाँ छ?", rom: "Mero raahadaanii kahaa~ chha?", eng: "Where is my passport?", tense: "present", theme: "travel" },
  { dev: "हामी होटलमा बस्यौं।", rom: "Haami hotalmaa basyau~.", eng: "We stayed at a hotel.", tense: "past", theme: "travel" },
  { dev: "ऊ ट्याक्सीमा आयो।", rom: "U tyaaksii maa aayo.", eng: "He came by taxi.", tense: "past", theme: "travel" },
  { dev: "मलाई बाटो थाहा छैन।", rom: "Malaaiii baato thaahaa chhaina.", eng: "I don't know the way.", tense: "present", theme: "travel" },
  { dev: "उनीहरू पहाडमा यात्रा गर्दैछन्।", rom: "Uniharuu pahaad maa yaatraa gardaichhan.", eng: "They are traveling in the mountains.", tense: "present", theme: "travel" },
  { dev: "हामीले नक्सा हेर्यौं।", rom: "Haamiile naksaa heryau~.", eng: "We looked at the map.", tense: "past", theme: "travel" },
  { dev: "ऊ मन्दिर हेर्न गयो।", rom: "U mandir herna gayo.", eng: "He went to see the temple.", tense: "past", theme: "travel" },
  { dev: "मैले धेरै देश घुमें।", rom: "Maile dherai desh ghume~.", eng: "I traveled to many countries.", tense: "past", theme: "travel" },
  { dev: "हामी बसमा काठमाडौं गयौं।", rom: "Haami basmaa kaathamaadau~ gayau~.", eng: "We went to Kathmandu by bus.", tense: "past", theme: "travel" },
  { dev: "उनले सामान होटलमा छोडिदिनुभयो।", rom: "Unle saamaan hotalmaa chhodidunubhayo.", eng: "He/she left the luggage at the hotel.", tense: "past", theme: "travel" },
  { dev: "पर्यटकहरू संग्रहालय हेर्न जान्छन्।", rom: "Paryatakaharu sangrahaalay herna jaanchhan.", eng: "Tourists go to see the museum.", tense: "present", theme: "travel" },
  { dev: "मौसम राम्रो भएपछि हामी जानेछौं।", rom: "Mausam raamro bhaepachhi haami jaanechhau~.", eng: "We will go when the weather is good.", tense: "future", theme: "travel" },
  { dev: "मैले गाइडलाई सोधें।", rom: "Maile gaaidlaaii sodhe~.", eng: "I asked the guide.", tense: "past", theme: "travel" },
  { dev: "ऊ गाउँमा फर्कनेछ।", rom: "U gaau~ maa pharknechha.", eng: "He will return to the village.", tense: "future", theme: "travel" },
  { dev: "हामीले धेरै फोटो खिच्यौं।", rom: "Haamiile dherai photo khichyau~.", eng: "We took many photos.", tense: "past", theme: "travel" },
  { dev: "विमानस्थलमा धेरै मान्छे थिए।", rom: "Wimaansthaal maa dherai maanchhe thie.", eng: "There were many people at the airport.", tense: "past", theme: "travel" },
  { dev: "म अर्को महिना फर्कनेछु।", rom: "Ma arko mahinaa pharknechhu.", eng: "I will return next month.", tense: "future", theme: "travel" },

];